language: python
python:
   - "3.7"
branches:
  only:
    - devel
install:
  - pip install -r requirements.txt
jobs:
  include:
    - stage: build_model
      script: python travis/tsv_to_sbml.py
    - stage: basic_tests
      script:
        - python travis/tsv_to_sbml.py
        - python travis/basic_fba.py
        - python travis/restricted_fba.py
    - stage: generate_report
      script: 
        - python travis/tsv_to_sbml.py
        - python travis/run_memote.py;
        - if [ $TRAVIS_PULL_REQUEST != "false" ]; then
            python travis/comment_script.py $GITHUB_TOKEN $TRAVIS_REPO_SLUG $TRAVIS_PULL_REQUEST $DISCORD_ENDPOINT $TRAVIS_BUILD_NUMBER $TRAVIS_BUILD_WEB_URL;
          else
            python travis/PR_merge.py $DISCORD_ENDPOINT $TRAVIS_BUILD_NUMBER $TRAVIS_BUILD_WEB_URL;
          fi
stages:
  - build_model
  - basic_tests
  - generate_report

after_failure:
  - python travis/failure_reporter.py $DISCORD_ENDPOINT $TRAVIS_BUILD_NUMBER $TRAVIS_BUILD_WEB_URL

# deploy:
#   - provider: pages
#     skip_cleanup: true
#     github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#     keep_history: true
#     on:
#       branch: devel
#       condition: $TRAVIS_PYTHON_VERSION = "3.7"
#     target_branch: gh-pages
